parameters:
    gitlab:
        default_branch:         '%env(GITLAB_DEFAULT_BRANCH)%'
        minimum_vote_up:        '%env(GITLAB_MINIMUM_VOTE_UP)%'
        auto_merge:             '%env(GITLAB_AUTO_MERGE)%'
        bot_username:           '%env(GITLAB_BOT_USERNAME)%'
        merge_must_be_approved: '%env(GITLAB_MERGE_MUST_BE_APPROVED)%'